<!-- 2011-11-10 預設模組各個Action Views內容架構 -->
<div id="content">
	search這是WEEK模組提供的預設畫面！<br/>
	<br/>
	功能描述：xxx
</div>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
		

<body>

<p>請設定查詢條件</p>
<fieldset id="feildOne"><!--區塊一：設定查詢項目-->
	<!--權限要是管理者才有（在AjaxController.php裡面判斷管理者才設定此變數）-->
		<!--權限要是管理者才有-->
	<input type="checkbox" conthree="dateSpan" value="dBlock" name="date"> 選擇日期範圍 <!--出現兩個日曆-->
	<input type="checkbox" conthree="monthSpan" value="mBlock" name="month"> 選擇月份範圍 <!--出現多選的月份，預設以當年度的月份為顯示基礎-->
	<input type="checkbox" conthree="yearSpan" value="yBlock" name="year"> 選擇年份範圍 <!--出現多選的年份（從2008年開始）-->
</fieldset>

<fieldset id="feildTwo"><!--區塊二：設定查詢條件-->
	<div class="feildTwo_div" id="uBlock" style="display: none;">
		<select size="6" multiple="multiple" name="select_users[]" id="select_users" disabled="">
					</select>
	</div>
	<div class="feildTwo_div" id="dBlock" style="display: none;">
		<input type="text" name="select_dateOne" id="select_dateOne" disabled="" class="dp-applied">
		&nbsp;到&nbsp;
		<input type="text" name="select_dateTwo" id="select_dateTwo" disabled="" class="dp-applied">
	</div>
	<div class="feildTwo_div" id="mBlock" style="display: none;">
		<select disabled="" size="5" multiple="multiple" name="select_months[]" id="select_months">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
						<option value="11">11</option>
						<option value="12">12</option>
					</select>
	</div>
	<div class="feildTwo_div" id="yBlock" style="display: none;">
		<select disabled="" size="3" multiple="multiple" name="select_years[]" id="select_years">
						<option value="2007">2007</option>
						<option value="2008">2008</option>
						<option value="2009">2009</option>
						<option value="2010">2010</option>
						<option value="2011">2011</option>
						<option value="2012">2012</option>
					</select>
	</div>
</fieldset>

<fieldset id="feildThree"><!--區塊三：顯示設定的查詢字串，中文解釋jquery處理-->
	<p>查詢週報條件
		<span id="userSpan" style="display: none;">找出<span id="userData" class="feildThree_span_span"></span> </span>
		<span id="yearSpan" class="feildThree_span" style="display: none;">時間在<span id="yearData" class="feildThree_span_span"></span>年間</span>
		<span id="monthSpan" class="feildThree_span" style="display: none;">時間在<span id="monthData" class="feildThree_span_span"></span>月份間</span>
		<span id="dateSpan" class="feildThree_span" style="display: none;">週次區間在<span id="dateData" class="feildThree_span_span"></span>範圍</span>
		的所有資料
	</p>
</fieldset>

<fieldset id="feildFour"><!--區塊四：顯示查詢統計結果並出現點選回畫面顯示，取回整個table-->
	<center> <input type="button" value="顯示查詢結果並關閉視窗" name="sendBtn" id="sendBtn"> </center>
</fieldset>

</form>

</body></html>