<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<style type="text/css">
</style>


<!-- 2011-11-10 預設模組各個Action Views內容架構 -->

<body>
 
<h1><?php echo $this->escape($this->title); ?></h1>
<?php if(!empty($this->message)):?>
	

<?php echo $this->escape($this->message);?>


<?php endif; ?>
<?php echo $this->form; ?>

 
</body>


</html>