<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<style type="text/css">
</style>
<header></header>
<body>


<ul class="nav_modules">
					<li class="frist" id="Wk">
					<a href="../week/manage/index"><img border="0" alt="請每週服用一次" src="../public/img/btnWk.png"></a></li>
					<li id="Mt">
					<a href="../month/manage/temp"><img border="0" alt="請每月服用一次" src="../public/img/btnMt.png"></a></li></ul>
					
					</body>
</html>