<html>
<head>
<title>線上行政系統--月報模組 v2.6b</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<meta content="IE=8" http-equiv="X-UA-Compatible">




</head>
<body>

<li><a href="http://oas.cc.scu.edu.tw/oas/month/manage/brokepoint">斷線紀
錄</a></li>
<li><a href="http://oas.cc.scu.edu.tw/oas/month/manage/workpoint">工作重點</a></li>
<!--2010-02-24 k1 判斷可彙整權限-->
<li><a href="http://oas.cc.scu.edu.tw/oas/index/login">回首頁</a></li>
<li><a href="http://oas.cc.scu.edu.tw/oas/index/logout">登出</a></li>
</ul>
</div>


<div class="month-query-block"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokequery"
class="thickbox" id="proc-query" title="月報模組--查詢紀錄">查詢斷線紀錄</a>
</div>
<span class="month-picker-block"> 設定編輯年月份
<div id="monthpicker" class="MonthPicker">
<table>
<tbody>
<tr>
<th class="caption">Year</th>
<td>
<ul>
<li class="li tyear"><!--[if IE 6]><a class="li" href="javascript:;"><table><tr><td><![endif]--><a
href="javascript:;"><span class="selected">2011</span></a>
<ul>
<li class="li"><a class="" title="2009" href="javascript:;">2009</a></li>
<li class="li"><a class="" title="2010" href="javascript:;">2010</a></li>
<li class="li"><a class="selected" title="2011"
href="javascript:;">2011</a></li>
<li class="li"><a class="" title="2012" href="javascript:;">2012</a></li>
<li class="li"><a class="" title="2013" href="javascript:;">2013</a></li>
<li class="li"><a class="" title="2014" href="javascript:;">2014</a></li>
</ul>
<!--[if IE 6]></td></tr></table></a><![endif]--></li>
</ul>
</td>
<th class="caption">Month</th>
<td class="month"><a title="1" href="javascript:;"><span class="">Jan</span></a><a
title="2" href="javascript:;"><span class="">Feb</span></a><a title="3"
href="javascript:;"><span class="">Mar</span></a><a title="4"
href="javascript:;"><span class="">Apr</span></a><a title="5"
href="javascript:;"><span class="">May</span></a><a title="6"
href="javascript:;"><span class="">Jun</span></a><a title="7"
href="javascript:;"><span class="">Jul</span></a><a title="8"
href="javascript:;"><span class="">Aug</span></a><a title="9"
href="javascript:;"><span class="">Sep</span></a><a title="10"
href="javascript:;"><span class="">Oct</span></a><a title="11"
href="javascript:;"><span class="selected">Nov</span></a><a title="12"
href="javascript:;"><span class="">Dec</span></a></td>
</tr>
</tbody>
</table>
</div>
<a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokeinsert"
class="thickbox" id="proc-insert" title="月報模組--新增紀錄">新增斷線紀錄</a>
</span>
<div id="content"><!--主要內容區塊：<BR />-->
<div id="content-broke">
<table class="tablesorter" id="broke-table" cellpadding="0"
cellspacing="1">
<thead> <tr>
<th class="th-user header">填報人</th>
<th class="th-date header">發生日期</th>
<th class="th-weekday">星期</th>
<th class="th-targetarea header">發生校區</th>
<th class="th-stoptype header">暫停服務種類</th>
<th class="th-stopreason header">停機事由</th>
<th class="th-process">執行功能</th>
</tr>
</thead> <tbody>
<tr class="tr-list" id="tr-1090"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1090-inputDate">2011-10-09</td>
<td id="1090-inputWeek" align="center">日</td>
<td id="1090-targetArea" align="center">全校</td>
<td id="1090-stopType" align="center">網路</td>
<td id="1090-stopReason">更新兩校區核心交換器</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1090"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1091"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1091-inputDate">2011-10-11</td>
<td id="1091-inputWeek" align="center">二</td>
<td id="1091-targetArea" align="center">雙溪</td>
<td id="1091-stopType" align="center">網路</td>
<td id="1091-stopReason">更新寵惠堂 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1091&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1091"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1092"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1092-inputDate">2011-10-11</td>
<td id="1092-inputWeek" align="center">二</td>
<td id="1092-targetArea" align="center">雙溪</td>
<td id="1092-stopType" align="center">網路</td>
<td id="1092-stopReason">更新文化樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1092&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1092"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1093"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1093-inputDate">2011-10-11</td>
<td id="1093-inputWeek" align="center">二</td>
<td id="1093-targetArea" align="center">雙溪</td>
<td id="1093-stopType" align="center">網路</td>
<td id="1093-stopReason">更新超庸館 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1093&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1093"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1094"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1094-inputDate">2011-10-11</td>
<td id="1094-inputWeek" align="center">二</td>
<td id="1094-targetArea" align="center">雙溪</td>
<td id="1094-stopType" align="center">網路</td>
<td id="1094-stopReason">更新愛徒樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1094&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1094"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1095"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1095-inputDate">2011-10-17</td>
<td id="1095-inputWeek" align="center">一</td>
<td id="1095-targetArea" align="center">雙溪</td>
<td id="1095-stopType" align="center">網路</td>
<td id="1095-stopReason">更新哲生樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1095&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1095"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1096"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1096-inputDate">2011-10-20</td>
<td id="1096-inputWeek" align="center">四</td>
<td id="1096-targetArea" align="center">雙溪</td>
<td id="1096-stopType" align="center">網路</td>
<td id="1096-stopReason">更新招待所光纖線路</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1096&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1096"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1097"
style="background-color: rgb(255, 255, 255); color: rgb(146, 146, 146);">
<td class="td-user">kiw</td>
<td id="1097-inputDate">2011-10-17</td>
<td id="1097-inputWeek" align="center">一</td>
<td id="1097-targetArea" align="center">雙溪</td>
<td id="1097-stopType" align="center">網路</td>
<td id="1097-stopReason">網路設備故障</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1097&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1097"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1098">
<td class="td-user">kiw</td>
<td id="1098-inputDate">2011-10-17</td>
<td id="1098-inputWeek" align="center">一</td>
<td id="1098-targetArea" align="center">雙溪</td>
<td id="1098-stopType" align="center">網路</td>
<td id="1098-stopReason">網路設備故障</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1098&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1098"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1099">
<td class="td-user">kiw</td>
<td id="1099-inputDate">2011-10-17</td>
<td id="1099-inputWeek" align="center">一</td>
<td id="1099-targetArea" align="center">雙溪</td>
<td id="1099-stopType" align="center">網路</td>
<td id="1099-stopReason">網路設備線路接觸不良</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1099&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1099"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1100">
<td class="td-user">phoebe1983</td>
<td id="1100-inputDate">2011-09-26</td>
<td id="1100-inputWeek" align="center">一</td>
<td id="1100-targetArea" align="center">全校</td>
<td id="1100-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1100-stopReason">webmail設備故障</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1100&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1100"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1101">
<td class="td-user">phoebe1983</td>
<td id="1101-inputDate">2011-10-21</td>
<td id="1101-inputWeek" align="center">五</td>
<td id="1101-targetArea" align="center">全校</td>
<td id="1101-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1101-stopReason">垃圾信防禦系統硬體故障</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1101&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1101"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1102">
<td class="td-user">yiting</td>
<td id="1102-inputDate">2011-10-19</td>
<td id="1102-inputWeek" align="center">三</td>
<td id="1102-targetArea" align="center">全校</td>
<td id="1102-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1102-stopReason">網域名稱伺服器異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1102&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1102"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1123">
<td class="td-user">kkboy</td>
<td id="1123-inputDate">2011-10-11</td>
<td id="1123-inputWeek" align="center">二</td>
<td id="1123-targetArea" align="center">城中</td>
<td id="1123-stopType" align="center">網路</td>
<td id="1123-stopReason">更換第四大樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1123&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1123"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1124">
<td class="td-user">kkboy</td>
<td id="1124-inputDate">2011-10-11</td>
<td id="1124-inputWeek" align="center">二</td>
<td id="1124-targetArea" align="center">城中</td>
<td id="1124-stopType" align="center">網路</td>
<td id="1124-stopReason">更換崇基樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1124&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1124"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1125">
<td class="td-user">kkboy</td>
<td id="1125-inputDate">2011-10-11</td>
<td id="1125-inputWeek" align="center">二</td>
<td id="1125-targetArea" align="center">城中</td>
<td id="1125-stopType" align="center">網路</td>
<td id="1125-stopReason">更換第六大樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1125&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1125"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1126">
<td class="td-user">kkboy</td>
<td id="1126-inputDate">2011-10-21</td>
<td id="1126-inputWeek" align="center">五</td>
<td id="1126-targetArea" align="center">城中</td>
<td id="1126-stopType" align="center">網路</td>
<td id="1126-stopReason">更換第三大樓 無線網路設備</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1126&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1126"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1127">
<td class="td-user">kkboy</td>
<td id="1127-inputDate">2011-10-21</td>
<td id="1127-inputWeek" align="center">五</td>
<td id="1127-targetArea" align="center">城中</td>
<td id="1127-stopType" align="center">網路</td>
<td id="1127-stopReason">更換崇基樓 無線網路設備光纖線</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1127&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1127"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1128">
<td class="td-user">tsuiting</td>
<td id="1128-inputDate">2011-10-19</td>
<td id="1128-inputWeek" align="center">三</td>
<td id="1128-targetArea" align="center">城中</td>
<td id="1128-stopType" align="center">網路</td>
<td id="1128-stopReason">更換城中校區無線網路認證閘道器</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1128&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1128"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1129">
<td class="td-user">tsuiting</td>
<td id="1129-inputDate">2011-10-19</td>
<td id="1129-inputWeek" align="center">三</td>
<td id="1129-targetArea" align="center">城中</td>
<td id="1129-stopType" align="center">網路</td>
<td id="1129-stopReason">更換城中校區無線網路認證閘道器</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1129&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1129"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1130">
<td class="td-user">tsuiting</td>
<td id="1130-inputDate">2011-09-30</td>
<td id="1130-inputWeek" align="center">五</td>
<td id="1130-targetArea" align="center">城中</td>
<td id="1130-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1130-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1130&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1130"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1131">
<td class="td-user">tsuiting</td>
<td id="1131-inputDate">2011-09-30</td>
<td id="1131-inputWeek" align="center">五</td>
<td id="1131-targetArea" align="center">城中</td>
<td id="1131-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1131-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1131&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1131"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1132">
<td class="td-user">tsuiting</td>
<td id="1132-inputDate">2011-09-30</td>
<td id="1132-inputWeek" align="center">五</td>
<td id="1132-targetArea" align="center">城中</td>
<td id="1132-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1132-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1132&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1132"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1133">
<td class="td-user">tsuiting</td>
<td id="1133-inputDate">2011-09-30</td>
<td id="1133-inputWeek" align="center">五</td>
<td id="1133-targetArea" align="center">城中</td>
<td id="1133-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1133-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1133&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1133"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1134">
<td class="td-user">tsuiting</td>
<td id="1134-inputDate">2011-09-30</td>
<td id="1134-inputWeek" align="center">五</td>
<td id="1134-targetArea" align="center">城中</td>
<td id="1134-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1134-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1134&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1134"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1135">
<td class="td-user">tsuiting</td>
<td id="1135-inputDate">2011-10-01</td>
<td id="1135-inputWeek" align="center">六</td>
<td id="1135-targetArea" align="center">城中</td>
<td id="1135-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1135-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1135&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1135"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1136">
<td class="td-user">tsuiting</td>
<td id="1136-inputDate">2011-10-01</td>
<td id="1136-inputWeek" align="center">六</td>
<td id="1136-targetArea" align="center">城中</td>
<td id="1136-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1136-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1136&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1136"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1137">
<td class="td-user">tsuiting</td>
<td id="1137-inputDate">2011-10-01</td>
<td id="1137-inputWeek" align="center">六</td>
<td id="1137-targetArea" align="center">城中</td>
<td id="1137-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1137-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1137&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1137"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1138">
<td class="td-user">tsuiting</td>
<td id="1138-inputDate">2011-10-01</td>
<td id="1138-inputWeek" align="center">六</td>
<td id="1138-targetArea" align="center">城中</td>
<td id="1138-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1138-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1138&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1138"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1139">
<td class="td-user">tsuiting</td>
<td id="1139-inputDate">2011-10-01</td>
<td id="1139-inputWeek" align="center">六</td>
<td id="1139-targetArea" align="center">城中</td>
<td id="1139-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1139-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1139&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1139"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1140">
<td class="td-user">tsuiting</td>
<td id="1140-inputDate">2011-10-01</td>
<td id="1140-inputWeek" align="center">六</td>
<td id="1140-targetArea" align="center">城中</td>
<td id="1140-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1140-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1140&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1140"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1141">
<td class="td-user">tsuiting</td>
<td id="1141-inputDate">2011-10-01</td>
<td id="1141-inputWeek" align="center">六</td>
<td id="1141-targetArea" align="center">城中</td>
<td id="1141-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1141-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1141&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1141"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1142">
<td class="td-user">tsuiting</td>
<td id="1142-inputDate">2011-10-01</td>
<td id="1142-inputWeek" align="center">六</td>
<td id="1142-targetArea" align="center">城中</td>
<td id="1142-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1142-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1142&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1142"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1143">
<td class="td-user">tsuiting</td>
<td id="1143-inputDate">2011-10-01</td>
<td id="1143-inputWeek" align="center">六</td>
<td id="1143-targetArea" align="center">城中</td>
<td id="1143-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1143-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1143&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1143"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1144">
<td class="td-user">tsuiting</td>
<td id="1144-inputDate">2011-10-01</td>
<td id="1144-inputWeek" align="center">六</td>
<td id="1144-targetArea" align="center">城中</td>
<td id="1144-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1144-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1144&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1144"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1145">
<td class="td-user">tsuiting</td>
<td id="1145-inputDate">2011-10-01</td>
<td id="1145-inputWeek" align="center">六</td>
<td id="1145-targetArea" align="center">城中</td>
<td id="1145-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1145-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1145&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1145"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
<tr class="tr-list" id="tr-1146">
<td class="td-user">tsuiting</td>
<td id="1146-inputDate">2011-10-02</td>
<td id="1146-inputWeek" align="center">日</td>
<td id="1146-targetArea" align="center">城中</td>
<td id="1146-stopType" align="center">伺服器故障、擴充、維修</td>
<td id="1146-stopReason">網頁服務異常</td>
<td align="center"> <a
href="http://oas.cc.scu.edu.tw/oas/month/manage/brokedetail?brokeid=1146&amp;keepThis=true&amp;modal=true&amp;TB_iframe=true&amp;height=500&amp;width=500"
class="thickbox" title="斷線紀錄--詳細內容" id="detail-1146"> 細節</a>&nbsp;<!--2010-02-24 k1 加入判斷是否為原發佈者才開啟「修改與刪除」--> </td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</body>
</html>

