<html><head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
		<title>thick box視窗</title>
		
	</head>
		<!--
2010-01-05
出現完整內容，尚須做排版處理！
-->
<body>
	發佈者：kiw 發佈時間2011-10-24 15:00:38 紀錄所屬報告月份2011-10
	<table width="80%" cellspacing="1" cellpadding="0" border="1" class="broke-table-1">
	<tbody>
	<tr>
		<th width="15%" class="th-date">日期</th>
		<td width="20%">2011-10-09</td>
		<th width="15%" class="th-weekday">星期</th>
		<td width="10%">日</td>
		<th width="15%" class="th-targetarea">發生校區</th>
		<td width="25%">全校</td>
	</tr>
	<tr>
		<th class="th-stoptype">暫停服務種類</th><td colspan="3">網路</td>
		<th class="th_title">公告次數</th><td>1</td>
	</tr>
	<tr>
	<th class="th-interrupt">服務中斷時間</th>
	<td colspan="3">08:30 到 17:00</td>
	<th class="th-passhour">經過時間</th>
	<td>8.50</td>
	</tr>
	<tr>
		<th colspan="6" class="th_title">說明</th><!--停機事由、中斷服務、影響區域-->
	</tr>
	<tr>
		<td colspan="6">自10-09 08:30～10-09 17:00 因更新兩校區核心交換器，暫停全校之有線及無線網路共8.50小時。</td>
	</tr>
	</tbody>
	</table>

	<center> <input type="button" value="關閉視窗" name="cancelBtn" id="cancelBtn"> </center>
</body></html>