<html><head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
		<title>thick box視窗</title>
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/datepicker.css" rel="stylesheet">
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/timepicker/timepicker.css" rel="stylesheet">
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/multiselect/jquery.multiSelect.css" rel="stylesheet">

		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jquery132.js" type="text/javascript"></script><!--改使用jQuery-->
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/date.js" type="text/javascript"></script>
<!--[if IE]><script type="text/javascript" src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/jquery.bgiframe.js"></script><![endif]-->
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/jquery.datepicker.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/timepicker/jquery.timePicker.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/jquery.dump.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/multiselect/jquery.multiSelect.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/month/ajax.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/month/adquery.js" type="text/javascript"></script>
		<script type="text/javascript">
			var URL = 'http://oas.cc.scu.edu.tw/oas/';
			var adquery_action = '';
			
			$(function(){
				$("#cancelBtn").click(function(){
					self.parent.tb_remove();
				});
			});
		</script>
	</head>
		<!--
2010-01-05
出現完整內容，尚須做排版處理！
-->
<body>
	發佈者：kiw 發佈時間2011-10-24 15:00:38 紀錄所屬報告月份2011-10
	<table width="80%" cellspacing="1" cellpadding="0" border="1" class="broke-table-1">
	<tbody>
	<tr>
		<th width="15%" class="th-date">日期</th>
		<td width="20%">2011-10-09</td>
		<th width="15%" class="th-weekday">星期</th>
		<td width="10%">日</td>
		<th width="15%" class="th-targetarea">發生校區</th>
		<td width="25%">全校</td>
	</tr>
	<tr>
		<th class="th-stoptype">暫停服務種類</th><td colspan="3">網路</td>
		<th class="th_title">公告次數</th><td>1</td>
	</tr>
	<tr>
	<th class="th-interrupt">服務中斷時間</th>
	<td colspan="3">08:30 到 17:00</td>
	<th class="th-passhour">經過時間</th>
	<td>8.50</td>
	</tr>
	<tr>
		<th colspan="6" class="th_title">說明</th><!--停機事由、中斷服務、影響區域-->
	</tr>
	<tr>
		<td colspan="6">自10-09 08:30～10-09 17:00 因更新兩校區核心交換器，暫停全校之有線及無線網路共8.50小時。</td>
	</tr>
	</tbody>
	</table>

	<center> <input type="button" value="關閉視窗" name="cancelBtn" id="cancelBtn"> </center>
</body></html>