<html><head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
		<title>thick box視窗</title>
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/datepicker.css" rel="stylesheet">
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/timepicker/timepicker.css" rel="stylesheet">
		<link href="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/multiselect/jquery.multiSelect.css" rel="stylesheet">

		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jquery132.js" type="text/javascript"></script><!--改使用jQuery-->
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/date.js" type="text/javascript"></script>
<!--[if IE]><script type="text/javascript" src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/jquery.bgiframe.js"></script><![endif]-->
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/datepicker/jquery.datepicker.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/timepicker/jquery.timePicker.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/jquery.dump.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/jplug/multiselect/jquery.multiSelect.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/month/ajax.js" type="text/javascript"></script>
		<script src="http://oas.cc.scu.edu.tw/oas/theme/js/month/adquery.js" type="text/javascript"></script>
		<script type="text/javascript">
			var URL = 'http://oas.cc.scu.edu.tw/oas/';
			var adquery_action = 'http://oas.cc.scu.edu.tw/oas/month/workpoint/process';
			
			$(function(){
				$("#cancelBtn").click(function(){
					self.parent.tb_remove();
				});
			});
		</script>
	<style type="text/css">
	fieldset{ width:95%; text-align:center;}
	
	#feildThree &gt; p &gt; span#userSpan{ text-align:left;}
	.feildTwo_div{ margin:3px;}
	.feildThree_span{ display:block; margin:0px;}
	.feildThree_span_span{ color:#00F;}
</style><script type="text/javascript">
	$(function(){
		adquery();
	});
</script></head>
		


<body>
<form name="form-query"><!--由父視窗呼叫Ajax程序！-->
	<input type="hidden" value="adquery" name="proc">
<p>請設定查詢條件</p>
<fieldset id="feildOne"><!--區塊一：設定查詢項目-->
	<!--權限要是管理者才有（在AjaxController.php裡面判斷管理者才設定此變數）-->
		<input type="checkbox" conthree="userSpan" value="uBlock" name="user"> 選擇使用者
	<input type="checkbox" conthree="typeSpan" value="cBlock" name="type"> 選擇資料類型
		<!--權限要是管理者才有-->
	<input type="checkbox" conthree="monthSpan" value="mBlock" name="month"> 選擇月份範圍 <!--出現多選的月份，預設以當年度的月份為顯示基礎-->
	<input type="checkbox" conthree="yearSpan" value="yBlock" name="year"> 選擇年份範圍 <!--出現多選的年份（從2008年開始）-->
</fieldset>

<fieldset id="feildTwo"><!--區塊二：設定查詢條件-->
	<div class="feildTwo_div" id="uBlock" style="display: none;">
		<select size="6" multiple="multiple" name="select_users[]" id="select_users" disabled="">
						<option value="k1">k1</option>
						<option value="tsung">tsung</option>
						<option value="tsuiting">tsuiting</option>
						<option value="yiting">yiting</option>
						<option value="kiw">kiw</option>
						<option value="kent">kent</option>
						<option value="kkboy">kkboy</option>
						<option value="phoebe1983">phoebe1983</option>
						<option value="cadalora">cadalora</option>
					</select>
	</div>
	<div class="feildTwo_div" id="cBlock" style="display: none;">
		<input type="radio" value="edit" checked="checked" name="select_type" id="radio_edit" disabled=""> 編輯資料
		&nbsp;&nbsp;
		<input type="radio" value="merge" name="select_type" id="radio_merge" disabled=""> 彙整資料
		&nbsp;&nbsp;
		<input type="radio" value="both" name="select_type" id="radio_both" disabled=""> 全部資料
	</div>
	<div class="feildTwo_div" id="mBlock" style="display: none;">
		<select disabled="" size="5" multiple="multiple" name="select_months[]" id="select_months">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
						<option value="11">11</option>
						<option value="12">12</option>
					</select>
	</div>
	<div class="feildTwo_div" id="yBlock" style="display: none;">
		<select disabled="" size="3" multiple="multiple" name="select_years[]" id="select_years">
						<option value="2007">2007</option>
						<option value="2008">2008</option>
						<option value="2009">2009</option>
						<option value="2010">2010</option>
						<option value="2011">2011</option>
						<option value="2012">2012</option>
					</select>
	</div>
</fieldset>

<fieldset id="feildThree"><!--區塊三：顯示設定的查詢字串，中文解釋jquery處理-->
	<p>查詢月報-工作重點 條件
		<span id="userSpan" style="display: none;">找出<span id="userData" class="feildThree_span_span"></span> </span>
		屬於<span id="typeData" class="feildThree_span_span" style="display: none;"></span> 
		<span id="yearSpan" class="feildThree_span" style="display: none;">時間在<span id="yearData" class="feildThree_span_span"></span>年間</span>
		<span id="monthSpan" class="feildThree_span" style="display: none;">時間在<span id="monthData" class="feildThree_span_span"></span>月份間</span>
		的所有資料
	</p>
</fieldset>

<fieldset id="feildFour"><!--區塊四：顯示查詢統計結果並出現點選回畫面顯示，取回整個table-->
	<center>
		<input type="button" value="顯示結果" name="sendBtn" id="sendBtn"> 
		<input type="button" value="關閉視窗" name="cancelBtn" id="cancelBtn"> 
	</center>
</fieldset>

</form>
</body></html>