<html><head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
		<title>thick box視窗</title>
		</head>
		

<body>
<div id="editArea">
	<form id="workForm">
		<input type="hidden" value="update" name="proc">
		<input type="hidden" value="3172" name="itemid">
		選擇主項次
		<select id="contentFormatId" name="contentFormatId">
									<option selected="selected" value="2">一、電子化校園專案執行說明</option>
																		<option value="4&quot;">二、校務行政系統開發說明</option>
												<option value="5&quot;">三、全校網路設備與相關系統說明</option>
												<option value="6&quot;">四、教職員生服務事項說明</option>
												<option value="7&quot;">五、協助校內其他單位說明</option>
								</select>
		<br>
		<textarea wrap="soft" id="content" name="content" cols="40" rows="10">ddd</textarea>
		<br>
		<center>
			<input type="button" value="顯示結果" name="sendBtn" id="sendBtn"> 
			<input type="button" value="關閉視窗" name="cancelBtn" id="cancelBtn"> 
		</center>
		<center><span id="volid-error"></span></center>
	</form>
</div>
</body></html>